/* The Quiet Wood — world layout. Generated by editor.html. */
window.MAP_DATA = {
  "seed": 20260713,
  "worldSize": 280,
  "props": [
    {
      "type": "tent",
      "x": 27,
      "z": -120
    }
  ],
  "riverX": 76,
  "pond": {
    "x": -187,
    "z": 74,
    "r": 22
  },
  "hill": {
    "x": 149,
    "z": -19
  },
  "bridgeZ": 55,
  "fire": {
    "x": 11,
    "z": 8
  },
  "cabin": {
    "x": -206,
    "z": 129
  },
  "campsite": {
    "x": 95,
    "z": -115
  },
  "blind": {
    "x": -116,
    "z": -29
  },
  "hollow": {
    "x": -170,
    "z": -170
  },
  "pieces": [
    {
      "x": -38,
      "z": -6
    },
    {
      "x": 33,
      "z": -1
    },
    {
      "x": -2,
      "z": -30
    },
    {
      "x": 2,
      "z": 30
    }
  ],
  "tallGrass": [
    {
      "x": 40,
      "z": -45
    },
    {
      "x": -55,
      "z": 20
    },
    {
      "x": 80,
      "z": 40
    },
    {
      "x": -20,
      "z": -70
    }
  ]
};
